title: xRegistry
description: The Extensible Registry for Metadata Management
baseurl: ""
url: "https://xregistry.io"
github_username: xregistry

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
plugins:
  - jekyll-remote-theme
  - jekyll-redirect-from

collections:
  articles:
    output: true
    permalink: /blog/:name/

article_series_size: 20

defaults:
  - scope:
      path: ""
      type: articles
    values:
      layout: article

# Slate theme settings
remote_theme: pages-themes/slate@v0.2.0

# Navigation
nav_items:
  - title: Home
    url: /
  - title: Blog
    url: /blog/
  - title: Core Spec
    url: /xreg/xregistryspecs/core-v1/docs/spec.html
  - title: Endpoint Spec
    url: /xreg/xregistryspecs/endpoint-v1/docs/spec.html
  - title: Schema Spec
    url: /xreg/xregistryspecs/schema-v1/docs/spec.html
  - title: Message Spec
    url: /xreg/xregistryspecs/message-v1/docs/spec.html
  - title: GitHub
    url: https://github.com/xregistry/spec

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - README.md
  - editorial/

favicon: https://github.com/cncf/artwork/raw/main/projects/xregistry/icon/color/xregistry-icon-color.svg
image: https://github.com/cncf/artwork/raw/main/projects/xregistry/horizontal/horizontal/color-whitetext/xregistry-horizontal-color-whitetext.svg
