name: Regen the xreg.io xreg files

on:
  repository_dispatch:
    types: [main_branch_updated]

jobs:
  update-repo:
    runs-on: duglin/xr-git
    permissions:
      contents: write # Required to push changes back

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run local script
        run: ./tools/buildsite

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@://github.com"
          
          git add .
          
          # Only commit if there are actual changes to prevent workflow failure
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "chore: automated update via remote trigger"
            git push
          else
            echo "No changes detected. Skipping push."
          fi
